### ISSUE TITLE
Support lazy loaded modules

### ISSUE THREAD

**Issue by andrewthauer** [rangle/augury-labs#28]
Lazy loaded modules cannot currently be profiled due to how `augury-labs` wraps the angular boostrap process on startup and looks for metadata in the registered modules. The same metadata / bootstrap process will need to also occur when a module is first loaded.

**Comment by maxime1992** [comment]
I'm getting the error:

```
An Error Occurred!
Cannot find module [module name]
```

With basically all the modules of my app. I think it's related to that issue because they're all lazy loaded.

That said, it should probably be considered as a bug and not enhancement, most of apps today are using lazy loaded modules

**Comment by andrewthauer** [comment]
Hi @maxime1992, thanks for your feedback. We definitely agree it is extremely common to have lazy loaded modules, so support for this is one of the top things on our radar to addresss.

Until then you should be able to temporarily work around this by importing the lazy loaded module(s) you would like to profile into your AppModule for the duration of the testing / profiling session.

Another (possibly cleaner) option which I just thought of (and have not tested) would be to create an AppAuguryModule that imports your AppModule along with the lazy loaded modules. This could then be bootstrapped in the main.augury.ts file instead of AppModule.

Understood this isn’t ideal but, but there are some technical hurdles we need to address to support this out of the box.

**Comment by maxime1992** [comment]
I currently have more than 60 modules so I'm not going to do that but glad it's "one of the top things on our radar to addresss" :) 

That project seems promising, good luck for the rest! :clap:

**Comment by stevenkampen** [comment]
@maxime1992 I'm looking into this now, and into support for lazy loaded modules in general, but I'm seeing something a little different than you describe. For me, the execution timeline is working as expected for modules that are lazily loaded via `loadChildren` (as per [this repo](https://github.com/rangle/angular-realworld-example-app-with-augury) but with `preloadingStrategy: NoPreloading`).

If you can share a demo app which recreates your error, or describe very clear reproduction steps, I'd like to check it out further.

**Comment by maxime1992** [comment]
Ha interesting! I, indeed, have a custom preloadingStrategy :smile_cat: !

Can't try right now but will give another shoot this week or the one after!

**Comment by stevenkampen** [comment]
@maxime1992 Out of interest, what does your custom PreloadingStrategy look like? I implemented a simple custom strategy with a timer which also works as expected. If you could give me something that causes the error you're talking about, that would be super helpful.

**Comment by maxime1992** [comment]
@stefannew sure.

We use that strategy to be able to preload by default, but if explicitely specified by a route: skip the preloading it.

```
export class PreloadSelectedModulesList implements PreloadingStrategy {
  public preload(route: CncRoute, load: () => Observable<any>): Observable<any> {
    return route.data && route.data.skipPreload
      ? of(null)
      : load().pipe(
          // no need to handle the error here because it's only the prefetch
          // if it fails, it'll then retry to fetch when actually needed
          // and if it fails again, that error will be handled by the global
          // error handler and properly displayed
          catchError(err => of(null)),
        );
  }
}
```

**Comment by stevenkampen** [comment]
@maxime1992 Weirdly, that preload strategy doesn't give me any issue either. I wonder what the difference is. If you can think of anything, or can be bothered "porting" the issue to some contrived project so I can reproduce it, let me know. Until then I guess we need more people to test it out.

**Comment by maxime1992** [comment]
Unfortunately the project I'm working on is not open source so I can't help much more than that. When I have some free time I might try on smaller side projects and see how it goes :+1:
